name: Build-Samples
on: push

jobs:
  build-linux:
    name: Build Samples for Linux x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Get Emscripten
        run: | 
          git clone https://github.com/emscripten-core/emsdk.git --depth=1
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: Build for web
        run: |
          source emsdk/emsdk_env.sh
          mkdir build
          cd build
          emcmake cmake ..
          cmake --build .
      - name: Prepare for upload
        run: |
           mkdir _site
           mv build/sdl-min.html _site/index.html
           mv build/sdl-* _site/
      - name: Fix permissions
        run: |
         chmod -c -R +rX "_site/" | while read line; do
           echo "::warning title=Invalid file permissions automatically fixed::$line"
         done
      - name: Upload 
        uses: actions/upload-pages-artifact@v2
        
